# Generated by Django 5.0.7 on 2024-10-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.IntegerField()),
                ('NAME', models.CharField(max_length=100)),
                ('BRANCH', models.CharField(choices=[('cse', 'Computer Science and Engineering'), ('ece', 'Electronics and Communication Engineering')], max_length=3)),
                ('SUBJECT', models.CharField(choices=[('pfsd', 'Professional Software Development'), ('mswd', 'Mobile Software Development')], max_length=4)),
            ],
        ),
    ]
